name: tmtcNOISEcorrc
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - matplotlib-base
  - mkl
  - numpy
  - pandas
  - pyteomics
  - python=3.8
  - scipy
  - seaborn-base
